In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.layers import Dense , Dropout
from keras.callbacks import EarlyStopping

In [31]:
df = pd.read_csv('housing.csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [32]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [33]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [34]:
df.isnull().sum()
df.dropna(inplace=True)

In [35]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [36]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9034
INLAND        6496
NEAR OCEAN    2628
NEAR BAY      2270
ISLAND           5
Name: count, dtype: int64

In [37]:
df['ocean_proximity'] = df['ocean_proximity'].map({'<1H OCEAN':0 , 'INLAND' :1 , 'NEAR OCEAN' :2 , 'NEAR BAY' :3 , 'ISLAND' :4})

In [38]:
df['ocean_proximity'].value_counts()

ocean_proximity
0    9034
1    6496
2    2628
3    2270
4       5
Name: count, dtype: int64

In [39]:
df['ocean_proximity'].head()

0    3
1    3
2    3
3    3
4    3
Name: ocean_proximity, dtype: int64

In [40]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,3
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,1
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,1
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,1
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,1
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,1

In [41]:
X = df.drop('median_house_value' ,axis=1)
y = df['median_house_value']

In [42]:
X = np.array(X)
y = np.array(y)

In [43]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=1)

# ***Scaling***

In [44]:
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
X_train

array([[0.20916335, 0.565356  , 0.92156863, ..., 0.07531656, 0.17529413,
        0.75      ],
       [0.46015936, 0.44845909, 0.56862745, ..., 0.05097846, 0.17931477,
        0.25      ],
       [0.21513944, 0.59404888, 0.07843137, ..., 0.22923861, 0.3069268 ,
        0.75      ],
       ...,
       [0.5876494 , 0.16365569, 1.        , ..., 0.02368032, 0.45914539,
        0.        ],
       [0.73505976, 0.1487779 , 0.54901961, ..., 0.09899688, 0.17539758,
        0.25      ],
       [0.21414343, 0.55791711, 0.66666667, ..., 0.06396974, 0.12439139,
        0.75      ]])

# ***Model Training***

In [46]:
model = Sequential()
model.add(Dense(1000 , input_shape=[X_train.shape[1]] , activation='relu'))
model.add(Dense(500 , activation='relu'))
model.add(Dense(250 , activation='relu'))
model.add(Dense(1 , activation='linear'))
model.compile(optimizer='adam' , loss='mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [47]:
callback = EarlyStopping(
    monitor = 'val_loss',
    min_delta = 0.00001 ,
    patience = 20 ,
    verbose = 1,
    mode = "min" ,
    baseline = None ,
    restore_best_weights = True
)

model.fit(X_train , y_train , validation_split=0.2 , epochs=30 , callbacks=[callback] , batch_size=32)

Epoch 1/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 38081622016.0000 - val_loss: 10107375616.0000
Epoch 2/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 9681595392.0000 - val_loss: 6747548672.0000
Epoch 3/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6418974208.0000 - val_loss: 5809528320.0000
Epoch 4/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5990662144.0000 - val_loss: 5529272832.0000
Epoch 5/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5409261056.0000 - val_loss: 5583286784.0000
Epoch 6/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - loss: 5413087232.0000 - val_loss: 5149619712.0000
Epoch 7/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5164397568.0000 - val_loss: 4970897920.0000
Epoch 8/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5288009728.0000 - val_loss: 4808372224.0000
Epoch 9/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 4821535744.0000 - val_loss: 4734991360.0000
Epoch 10/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 4733351936.0000 - val_loss: 4643775488.0000
Epoch 11/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - loss: 4575232512.0000 - val_loss: 4787752960.0000
Epoch 12/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - loss: 4537882112.0000 - val_loss: 4417573888.0000
Epoch 13/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 9s 12ms/step - loss: 4369402368.0000 - val_loss: 4512245248.0000
Epoch 14/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 4359889408.0000 - val_loss: 4390542848.0000
Epoch 15/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 4410854400.0000 - val_loss: 4348521984.0000
Epoch 16/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 4339452928.0000 - val_loss: 4337703936.0000
Epoch 17/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4556846080.0000 - val_loss: 4393665024.0000
Epoch 18/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4216103936.0000 - val_loss: 4419652096.0000
Epoch 19/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 4380912640.0000 - val_loss: 4339950592.0000
Epoch 20/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4347468800.0000 - val_loss: 4293977088.0000
Epoch 21/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 4355302400.0000 - val_loss: 4409593856.0000
Epoch 22/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4362307072.0000 - val_loss: 4383466496.0000
Epoch 23/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4295343616.0000 - val_loss: 4358108160.0000
Epoch 24/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 4343394816.0000 - val_loss: 4256724736.0000
Epoch 25/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 4303983616.0000 - val_loss: 4243510784.0000
Epoch 26/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 4085710592.0000 - val_loss: 4313522176.0000
Epoch 27/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 4216829696.0000 - val_loss: 4250055424.0000
Epoch 28/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 4286539008.0000 - val_loss: 4235389696.0000
Epoch 29/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - loss: 4231841792.0000 - val_loss: 4249986816.0000
Epoch 30/30
409/409 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - loss: 4189300736.0000 - val_loss: 4206443520.0000
Restoring model weights from the end of the best epoch: 30.

# ***Results***

In [48]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,mean_squared_log_error

y_pred = model.predict(X_test)
print("mae :", mean_absolute_error(y_test,y_pred))
print("mse :", mean_squared_error(y_test,y_pred))
print("mae :", mean_squared_log_error(y_test,y_pred))
print("score :", r2_score(y_test,y_pred))

128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
mae : 45279.36425422835
mse : 4163569431.7116475
mae : 0.09684776362987606
score : 0.6868758124591321

# ***Prediction function***

In [49]:
def pred(longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity):
    features = np.array([longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity])
    features_scaled = scaler.transform([features])
    results = model.predict(features_scaled)
    return results[0]

In [50]:
longitude = -122.2300
latitude  = 37.8800
housing_median_age  = 41.0000
total_rooms        = 880.0000
total_bedrooms   =  129.0000
population     = 322.0000
households          =    126.0000
median_income       =      8.3252
ocean_proximity       =     3.0000

price = pred(longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step

In [51]:
price

array([421190.2], dtype=float32)

In [52]:
model.save("model_ann.h5")

import pickle
pickle.dump(scaler, open('scaler.pkl', 'wb'))

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [53]:
import gradio as gr

In [63]:
import numpy as np
import gradio as gr
import pickle
from tensorflow.keras.models import load_model
from tensorflow.keras.models import load_model
from tensorflow.keras.losses import MeanSquaredError

model = load_model("model_ann.h5", custom_objects={'mse': MeanSquaredError()})


# Load model and scaler
model = load_model("model_ann.h5" , custom_objects={'mse': MeanSquaredError()})
scaler = pickle.load(open("scaler.pkl", "rb"))

# Map labels to numeric values
ocean_map = {
    '<1H OCEAN': 0,
    'INLAND': 1,
    'NEAR OCEAN': 2,
    'NEAR BAY': 3,
    'ISLAND': 4
}

# Reverse map for UI dropdown (optional, if needed)
ocean_labels = list(ocean_map.keys())

# Define prediction function
def predict_price(longitude, latitude, housing_median_age, total_rooms,
                  total_bedrooms, population, households, median_income, ocean_proximity):
    try:
        ocean_encoded = ocean_map[ocean_proximity]  # Convert label to number

        # Create input array
        input_data = np.array([[longitude, latitude, housing_median_age,
                                total_rooms, total_bedrooms, population,
                                households, median_income, ocean_encoded]])

        # Ensure values are within training range
        input_data = np.clip(input_data, scaler.data_min_, scaler.data_max_)

        # Scale input
        input_scaled = scaler.transform(input_data)

        # Predict
        prediction = model.predict(input_scaled)[0][0]
        return f"🏠 Predicted House Value: ${prediction:,.2f}"

    except Exception as e:
        return f"❌ Error: {str(e)}"

# Gradio interface
inputs = [
    gr.Number(label="Longitude"),
    gr.Number(label="Latitude"),
    gr.Number(label="Housing Median Age"),
    gr.Number(label="Total Rooms"),
    gr.Number(label="Total Bedrooms"),
    gr.Number(label="Population"),
    gr.Number(label="Households"),
    gr.Number(label="Median Income"),
    gr.Dropdown(choices=ocean_labels, label="Ocean Proximity")
]

output = gr.Textbox(label="Prediction")

# Launch interface
gr.Interface(fn=predict_price, inputs=inputs, outputs=output, title="California House Price Predictor").launch()

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://ee6515fce0df39ef68.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)